[package]
name = "simple-serve"
version = "0.1.0"
authors = ["Marcelo Lima <marcelowind@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "3", features = [ "derive" ] }
tokio = { version = "1", features = [ "macros", "rt-multi-thread" ] }
warp = "0.3"
